### ISSUE TITLE
pixel art

### ISSUE THREAD

**Issue by 5alidshammout** [lunapaint/vscode-luna-paint#111]
I've done this pixel art using an app
![image](https://user-images.githubusercontent.com/73162518/144785775-dc6dc785-977c-46d7-b942-0665badda3aa.png)
I wanted to edit using lunapaint but the problem was the grid size doesn't equal the size of a pixel I drew, so can you please make the grid pixel size editable

**Comment by Tyriar** [comment]
Thanks for trying out the extension!

Normally when you do pixel art you should size the image down such that a single pixel in your artwork is a pixel in the grid, this will make it a lot easier to work with as well since the pencil tool only has a 1x1 size right now as well. You can then resize the image up when you're done using nearest neighbor, or scale up the artwork in your app.

A customizable grid might come at some point, but I think right now it's out of scope to keep things simple and avoid bloat.

**Comment by 5alidshammout** [comment]
ok, thanks
