### ISSUE TITLE
Allow for easier cropping of image

### ISSUE THREAD

**Issue by misolori** [lunapaint/vscode-luna-paint#41]
A lot of design tools have a crop tool to easily resize the frame. This would be useful to have an easy way to resize, currently you have to go through bottom right and answer the quick pick width/height questions (which are a bit annoying when you're working quickly)

**Figma**
<img width="400" src="https://user-images.githubusercontent.com/35271042/113785842-c6ff4b00-96ec-11eb-97fa-6325317ebd00.png">

**Photoshop**
<img width="100" src="https://user-images.githubusercontent.com/35271042/113786012-28271e80-96ed-11eb-91d4-d9171ae2237f.png">

**Sketch**
They allow the entire canvas to be resized and have width/height in a panel
![image](https://user-images.githubusercontent.com/35271042/113786354-d206ab00-96ed-11eb-9f45-9a4bc1c1b8e0.png)

**Comment by Tyriar** [comment]
cmd+shift+x will crop (or via menu/command palette), new in v0.4.0 adds it to the selection and move selection tools as well:

![image](https://user-images.githubusercontent.com/2193314/113791070-aee0f900-96f7-11eb-9411-3e2c5471aa31.png)

Also a few days ago I was considering adding a crop tool as well and potentially having it as a good candidate to be hidden by default since there are several other ways to do it, just have it available for those that like to make a selection and crop automatically.

As for the sketch idea I could do something like that as well but I worry about too much going on in the canvas as once. When what tools are focused would you expect the corner hot spots to be visible? Move pixels/selection has similar hot spots and when you're using a pencil/rectangle it wouldn't be good either. Open to ideas 🙂
