### ISSUE TITLE
Add change line width function for brush and line tool 

### ISSUE THREAD

**Issue by scaevitas** [lunapaint/vscode-luna-paint#63]
it would be helpful to be able to change the line width similar to the rectangle tool and the eraser tool. Thank you so much!

**Comment by Lord-Scrubington-II** [comment]
This is a bit of an old issue, but I agree! This would vastly improve the amount of things I can use Luna Paint to do. Thanks!

**Comment by Tyriar** [comment]
This has since been added for the line tool:
![recording (3)](https://user-images.githubusercontent.com/2193314/143691834-294df3bb-f2c7-4b41-af27-bdc0c94d6118.gif)

There is a pencil which is focused on more on pixel art/pixel-perfect strokes and may not end up getting a width. I think we can close this off in favor of a brush tool feature https://github.com/lunapaint/vscode-luna-paint/issues/20 where brush size will be a must.
