### ISSUE TITLE
Add documentation for how to configure for Figma users

### ISSUE THREAD

**Issue by jt3k** [lunapaint/vscode-luna-paint#74]
Issue Type: <b>Bug</b>
please fix the keyboard shortcuts so this mimics figma and not photoshop 

Extension version: 0.6.0
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (16 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (2.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jt3k** [comment]
also we have aggressive scrolling with mouse wheel on mac,

**Comment by Tyriar** [comment]
@jt3k any particular shortcuts you think should be different? I haven't used Figma much.

On the mouse wheel, I'll need to follow that up at home with my bluetooth mouse https://github.com/lunapaint/vscode-luna-paint/issues/75

@misolori any opinions?

**Comment by misolori** [comment]
Here are the shortcuts from Figma's tools:

<img width="1068" alt="CleanShot 2021-06-11 at 08 21 58@2x" src="https://user-images.githubusercontent.com/35271042/121710153-259ac980-ca8e-11eb-991d-7abe7c81c70c.png">

I mean one could manually re-map these but as someone who uses FIgma, I don't think I'd expect for this extension to map to those keymaps because they feel like different tools.

**Comment by Tyriar** [comment]
I agree with you that the standard PS/other editor inspired shortcuts make more sense. Maybe this could be some documentation somewhere with a json dump to add all these keybindings easily (since extension keymaps aren't really a thing). It could also be a command but seems overkill.

**Comment by jt3k** [comment]
this is my subjective opinion.
because I'm used to zooming in using [cmd] + mouse-wheel,
as well as panning using pressing the spacebar and dragging with the mouse.

I can of course try to argue with the fact that nobody uses Photoshop to create layouts for the web, but I won't :)

**Comment by Tyriar** [comment]
@jt3k I think zooming and panning work the same as Figma by default, you can swap the zoom and scroll modifiers though. I've been considering for a while how to configure mouse modifiers since lots of different editors use different schemes and it's a annoyance of mine jumping into Photoshop for example which uses alt+wheel to zoom when I'm used to ctrl. Created https://github.com/lunapaint/vscode-luna-paint/issues/80 to track that.

**Comment by jt3k** [comment]
ok, what about the keymap preset feature? Let's create an issue like this. We could determine how many users prefer a keymap other than the default. And this will help us make the right choice when installing the default preset in the future.

**Comment by Tyriar** [comment]
I think you can only have one keymap extension active, so they don't really work to override an extension's keybindings as it would leave people using another one in the dark.
